export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_LOGIN_SUCCESS = "REQUEST_LOGIN_SUCCESS";
export const REQUEST_LOGIN_FAILURE = "REQUEST_LOGIN_FAILURE";

export const REQUEST_LOGOUT_SUCCESS = "REQUEST_LOGOUT_SUCCESS";

export const REQUEST_ACCOUNT = "REQUEST_ACCOUNT";
export const RECEIVE_ACCOUNT = "RECEIVE_ACCOUNT";
export const REQUEST_ACCOUNT_FAILURE = "REQUEST_ACCOUNT_FAILURE";

export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_FAILED = "CREATE_ACCOUNT_FAILED";

export const UPDATE_ACCOUNT_BALANCE_REQUEST = "UPDATE_ACCOUNT_BALANCE_REQUEST";
export const UPDATE_ACCOUNT_BALANCE_SUCCESS = "UPDATE_ACCOUNT_BALANCE_SUCCESS";
export const UPDATE_ACCOUNT_BALANCE_FAILED = "UPDATE_ACCOUNT_BALANCE_FAILED";
